AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    dynamodb_event_reader

    Sample SAM Template for dynamodb_event_reader to interact with DynamoDB Events.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5

Resources:
    ReadDynamoDBEvent:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: read_dynamodb_event/
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                DynamoDBEvent:
                    Type: DynamoDB # More info about DynamoDB Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#dynamodb
                    Properties:
                        Stream:
                            !GetAtt DynamoDBTable.StreamArn
                        StartingPosition: TRIM_HORIZON
                        BatchSize: 10
            Environment:
                Variables:
                    TABLE_NAME: !GetAtt DynamoDBTable.TableName
    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        StreamSpecification:
            StreamViewType: NEW_AND_OLD_IMAGES
        Properties:
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
                - AttributeName: modifiedDate
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
                - AttributeName: modifiedDate
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST